"""
fix_math_animation_stubs.py
Insert "## Animation" section stub immediately after the "## 0 · The Challenge"
heading in each Math Under the Hood chapter README.md.

Skips ch04 and ch06 which already have inline GIF references inside their content
(wraps them with a section header instead if ## Animation is absent).
"""
import re
import os
import glob

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATH_ROOT = os.path.join(REPO_ROOT, "notes", "math_under_the_hood")

MD_FILES = sorted([
    f for f in glob.glob(os.path.join(MATH_ROOT, "**", "README.md"), recursive=True)
    if os.path.dirname(f) != MATH_ROOT
])

CHALLENGE_HEADING = re.compile(r"(^## 0 · The Challenge[^\n]*\n)", re.MULTILINE)

def get_animation_stub(chapter_name: str) -> str:
    return (
        f"\n## Animation\n\n"
        f"> 🎬 *Animation placeholder — see `img/{chapter_name}-animation.gif`"
        f" — generated by needle-builder agent.*\n\n"
    )

for filepath in MD_FILES:
    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    if "## Animation" in content:
        print(f"Already has ## Animation: {os.path.relpath(filepath, REPO_ROOT)}")
        continue

    chapter_name = os.path.basename(os.path.dirname(filepath))

    match = CHALLENGE_HEADING.search(content)
    if not match:
        print(f"No ## 0 · The Challenge found in {os.path.relpath(filepath, REPO_ROOT)}")
        continue

    insert_pos = match.end()
    stub = get_animation_stub(chapter_name)
    new_content = content[:insert_pos] + stub + content[insert_pos:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Inserted ## Animation stub in {os.path.relpath(filepath, REPO_ROOT)}")

print("Done.")
