"""
generate_all_fix_scripts.py
───────────────────────────
Reads every plan.md under notes/ that contains a SCRIPTS_HOOK_START block,
extracts the script table rows, and generates stub Python fix scripts under
scripts/ for any that don't already exist.

Usage:
    python scripts/generate_all_fix_scripts.py [--dry-run]

Options:
    --dry-run   Print what would be created without writing files.
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTES_DIR = REPO_ROOT / "notes"
SCRIPTS_DIR = REPO_ROOT / "scripts"

HOOK_RE = re.compile(
    r"<!-- SCRIPTS_HOOK_START\s*track:\s*(?P<track>[^\n]+)\s*-->"
    r"(?P<table>.*?)"
    r"<!-- SCRIPTS_HOOK_END -->",
    re.DOTALL,
)

TABLE_ROW_RE = re.compile(
    r"^\|\s*`(?P<script>[^`]+\.py)`\s*\|"
    r"\s*(?P<files>[^|]+)\s*\|"
    r"\s*(?P<description>[^|]+)\s*\|",
    re.MULTILINE,
)

STUB_TEMPLATE = '''\
"""
{script_name}
{underline}
Track : {track}
Target: {files}

Purpose
-------
{description}

Generated by: scripts/generate_all_fix_scripts.py
Run with   : python scripts/{script_name}

TODO: Replace the stub body below with the actual transformation logic.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    print("Running {script_name}...")
    # TODO: implement the transformation
    # Example pattern:
    #
    #   for path in REPO_ROOT.glob("notes/**/*.md"):
    #       text = path.read_text(encoding="utf-8")
    #       updated = text.replace("old string", "new string")
    #       if updated != text:
    #           path.write_text(updated, encoding="utf-8")
    #           print(f"  Updated {{path.relative_to(REPO_ROOT)}}")
    #
    print("Done.")


if __name__ == "__main__":
    main()
'''


def parse_plan_files(notes_dir: Path) -> list[dict]:
    """Return list of {track, script, files, description} dicts from all plan.mds."""
    entries: list[dict] = []
    for plan_path in sorted(notes_dir.rglob("plan.md")):
        text = plan_path.read_text(encoding="utf-8")
        for hook_match in HOOK_RE.finditer(text):
            track = hook_match.group("track").strip()
            table_text = hook_match.group("table")
            for row_match in TABLE_ROW_RE.finditer(table_text):
                script = row_match.group("script").strip()
                files = row_match.group("files").strip()
                description = row_match.group("description").strip()
                entries.append(
                    {
                        "plan_file": plan_path,
                        "track": track,
                        "script": script,
                        "files": files,
                        "description": description,
                    }
                )
    return entries


def generate_script(entry: dict, scripts_dir: Path, dry_run: bool) -> Path:
    """Write a stub Python script. Returns the script path."""
    script_path = scripts_dir / Path(entry["script"]).name
    if script_path.exists():
        print(f"  SKIP  {script_path.relative_to(REPO_ROOT)}  (already exists)")
        return script_path

    script_name = script_path.name
    underline = "-" * len(script_name)
    stub = STUB_TEMPLATE.format(
        script_name=script_name,
        underline=underline,
        track=entry["track"],
        files=entry["files"],
        description=entry["description"],
    )

    if dry_run:
        print(f"  DRY-RUN  would create  {script_path.relative_to(REPO_ROOT)}")
    else:
        script_path.write_text(stub, encoding="utf-8")
        print(f"  CREATE  {script_path.relative_to(REPO_ROOT)}")

    return script_path


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print actions without writing files.",
    )
    args = parser.parse_args(argv)

    entries = parse_plan_files(NOTES_DIR)
    if not entries:
        print("No SCRIPTS_HOOK blocks found in any plan.md — nothing to generate.")
        sys.exit(0)

    print(f"Found {len(entries)} script todos across all plan.md files.\n")

    if not args.dry_run:
        SCRIPTS_DIR.mkdir(exist_ok=True)

    generated: list[Path] = []
    for entry in entries:
        path = generate_script(entry, SCRIPTS_DIR, dry_run=args.dry_run)
        generated.append(path)

    print(f"\n{'DRY-RUN: ' if args.dry_run else ''}{len(generated)} script(s) processed.")
    print("\nNext steps:")
    print("  1. Open each generated script under scripts/ and implement the TODO body.")
    print("  2. Run the scripts in the order shown in notes/scripts-gist.md.")


if __name__ == "__main__":
    main()
